### PR TITLE
Fix ss singular noun

### LINKED ISSUE #159: Incorrect singular_noun behavior?
```

import inflect as Inflect
inflect = Inflect.engine()
inflect.singular_noun("car")           # get False, as expected
inflect.singular_noun("mass")          # get "mas", expected False

```

Is this behavior a bug?  singular_noun() is supposed to return False when the word is already singular, and I can find no reference to suggest "mass" is the plural of "mas", which is itself the plural of "ma".

### PR DESCRIPTION
**Pull request by george-gca**
Fixes #159

### CODE REVIEW

**Comment by jaraco** [comment]
Thanks for the contrib. Can you add a test that would fail without these fixes? It may be as simple as adding the known bad cases to inflections.txt.

**Comment by george-gca** [comment]
@jaraco since this fix is for a case where the word is already in singular, just adding it to the inflections.txt cover it, right?

**Comment by jaraco** [comment]
> @jaraco since this fix is for a case where the word is already in singular, just adding it to the inflections.txt cover it, right?

Honestly, I don't know. Probably?

**Comment by jaraco** [comment]
This one is so close. Would someone be willing to track down a test that characterizes the failure and fails on main but passes here?

**Comment by george-gca** [comment]
I'd love to. I just forgot to check if that was enough to create the test and run it. But I am going to be afk untill 22nd this month. If no one does it first, I will do it as soon as I come back.

**Comment by jaraco** [comment]
Friendly nudge.

**Comment by george-gca** [comment]
Can you help me setup a dev environment for this package? This way I could also write the tests and check if it is working correctly.

**Comment by jaraco** [comment]
The easiest way to get set up with a dev environment is to get [tox](https://tox.wiki/en/latest/). I personally use [pipx](https://pypi.org/project/pipx/) to install tox, but there are many other ways (including system package managers). Once you have tox and a clone/fork of the repo, simply run `tox` in the `inflect` project directory. That will run all of the tests. Presumably, they should pass if you haven't changed anything. If that's not the case, you'll probably want to investigate why the tests aren't passing to ensure they're passing (first check to see if there are similar failures [in CI](https://github.com/jaraco/inflect/actions)). After you've run the tests, you'll be left with a `.tox/py` directory, which is a virtualenv with `inflect` editable-installed, meaning you can run `.tox/py/bin/python` and have an environment that can `import inflect` and get the project as you have checked-out and edited.

After you've written a test, just run `tox` again and see if it passes or fails. To make things faster, you can run `tox -- -k <my test name>`, which passes a keyword to pytest saying "only run tests containing <my test name>". Any parameters after `--` get passed to pytest. You can also pass `--pdb` to pytest, which will give you a Pdb prompt any time a test fails, useful for inspecting the state of affairs at the point the test fails.

I hope that helps. Let me know if you have any trouble.

**Comment by jaraco** [comment]
I'm going to close this for now, but feel free to revive it when you have interest/time.

**Pull request closed without merging**
