### PR TITLE
Fix s plural noun

### LINKED ISSUE #161: Words ending in 's' should never be pluralized by adding another 's'
stockings -> stockingss
jeans -> jeanss
sandals -> sandalss

How do I avoid this? I can fix the specific words with defnoun('jeans', 'jeans'), which corrects the result for an isolated string 'jeans' -> 'jeans'.

However, if I try to run plural_noun on 'blue jeans' instead of 'jeans' it then breaks again, returning 'blue jeanss'. I understand this is because 'blue jeans' appears to be a different string from 'jeans', but perhaps it should check the rules for the part of the string it is altering?

I've gotten around this so far by this incredibly hacky 'solution', so any improvement would obviously be immensely appreciated:
```
            plural = _INFLECT.plural_noun(key, count)
            if plural.endswith('ss'):
                plural = plural[0:-1]
```

### PR DESCRIPTION
**Pull request by george-gca**
Fixes #161

### CODE REVIEW

**Review by jaraco — CHANGES_REQUESTED** [review]
Looks good. Thanks for the contrib. Can you add a test that captures the known bad cases (fails before and passes after this change)?

**Comment by george-gca** [comment]
Sure, but some of the failing cases are already there. I gave a quick look at your testing code and couldn't understand it, so I need to do a deep dive. Does your test code test the opposite, and also the same case? I mean, for example:
> bass -> basses

Does your testing code tests

>singular(bass)
>plural(bass)
>singular(basses)
>plural(basses)

?

**Comment by jaraco** [comment]
> Sure, but some of the failing cases are already there. I gave a quick look at your testing code and couldn't understand it, so I need to do a deep dive. Does your test code test the opposite, and also the same case? I mean, for example:
> 
> > bass -> basses
> 
> Does your testing code tests
> 
> > singular(bass)
> > plural(bass)
> > singular(basses)
> > plural(basses)
> 
> ?

I'm not sure, but I'm guessing not. Historically, the project assumes valid inputs, so a call of `singular(bass)` or `plural(basses)` is considered invalid. That is, the project doesn't perform general-purpose semantic language comprehension, but instead provides simple inflection given known inputs.

I'm happy to accept more sophistication, but the status quo is somewhat limited.

**Comment by george-gca** [comment]
Actually some of the failing cases are like you said, `singular(bass)` or `plural(basses)`. I will give it a thought about how to do some kind of verification before doing singularization/pluralization.

**Comment by george-gca** [comment]
Added test cases like `jeans -> jeans`

**Comment by jaraco** [comment]
Oops. I merged this not double-checking the tests and I see now they're failing, so I've force-pushed without those changes. Please re-submit.

**Pull request merged**
