### PR TITLE
Restore copyright notice in main module

### PR DESCRIPTION
**Pull request by jayaddison**
With [reference to this note from @pwdyson](https://github.com/jaraco/inflect/commit/e640d3a08b1e55095be378b4f4b6e4b6806eb7fb#r120831163) re: the removal of this notice:

> Thanks James for drawing my attention to this. The copyright and my name should not be removed. Please put it back.

This reverts commit e640d3a08b1e55095be378b4f4b6e4b6806eb7fb.

### CODE REVIEW

**Comment by jaraco** [comment]
Thanks for the ping. Let's first start with an issue where we can discuss the implications and tradeoffs.

**Comment by pwdyson** [comment]
Please restore my name and copyright notice. Then we can discuss any changes.

**Comment by pwdyson** [comment]
First, let me say thanks for continuing to maintain this project. Without your work to keep this package up to date, what I state below would not be possible.

I feel pretty strongly about keeping my copyright notice on this package. However, I am not against other people being acknowledged, either by name or in some sort of generic statement. We can discuss the wording.

There are a number of reasons for wanting to keep the copyright statement, but here is just one.

Having my name there increases my professional reputation. I am a software engineer working in a large corporation. As you would expect, our internal code repository does not include the names of the employees who work on the code. However, if you search the repository for my name, it is there, because inflect is one of the many third party software libraries the corporation uses. So I can ask colleagues to search for my name in the code repository and they find it. This has a “Wow!” factor that impresses people and enhances my professional reputation. Removing my name reduces my professional reputation as I could no longer do this at work. I am hoping that my work does not ingest a current version of inflect without my name on it. To prevent this from happening I want the copyright notice restored as soon as possible.

This needs to be a copyright notice because not all of the files in the project are kept by my employer. Copyright, however, is something that large corporations respect and will not remove.

The year 2010 enhances my reputation as it shows I’ve been around for a while. This is seen favourably, particularly by many employees in their 20s that I work with. Also, it is a soft signal to legal that I am not working on this code any more and so the corporation does not have any ownership of the code.

**Comment by jayaddison** [comment]
The way I'd think of it is: think of a book, document or article that has someone's name attached to it as one of the authors.  If you were that person, would you be OK with your name being removed when the article is being reprinted in an updated format, because it's more convenient for the publisher?

I think that the vast majority of people would say 'no' - they'd prefer their name to be retained on the work.  That's independent or not or what public opinion is about them and any claims that the publisher makes in that regard -- it can be equally important to remember what someone said, regardless of how history views them.  In addition, some people might under some circumstances be OK with their name being removed - or even want it to be.  Those situations could indicate some other kind of problem, but it's unclear what the nature of that might be.

Either way: if Paul has expressed an opinion for his name to remain in the copyright notices for the work, and if the two if you have not agreed and confirmed to remove it, then I think that it should stay in place.

**Comment by jayaddison** [comment]
Quoting from https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects :

```
Don’t change someone else’s copyright notice without their permission

You should not change or remove someone else’s copyright notice unless they have expressly (in writing) permitted you to do so. This includes third parties’ notices in pre-existing code.
```

**Comment by jaraco** [comment]
See https://github.com/jaraco/inflect/issues/197#issuecomment-1685122063, where I lay out the plan.

**Pull request merged**
